### ISSUE TITLE
Alembic migrations

### ISSUE THREAD

**Issue by ergo** [Pylons/pyramid-cookiecutter-alchemy#5]
As per this ticket https://github.com/Pylons/pyramid/pull/1625.

Would an approach like this sound reasonable?

https://code.rhodecode.com/rhodecode-appenlight/files/58cb9fcf39dff182fd74dead41df90a3e091ff16/backend/src/appenlight/scripts/migratedb.py#L37

This is what I used in the past and could port the code into cookiecutter.
I would like some feedback on this.

**Comment by stevepiercy** [comment]
It sounds reasonable.

Would you present an option to the user to use alembic, or would it be included regardless?

**Comment by mmerickel** [comment]
I don't actually think the linked approach is appropriate for the cookiecutter because it changes the workflow quite a bit from the default documented one in alembic's docs. I would prefer a setup that did not wrap the alembic cli in a new script - at least to begin with.

1. This script bootstraps the wsgi app which means it establishes a database session before the migrations are run. This does not extend well if a user does any database queries in their app setup.

2. This script does not support creating new migrations or any of the several other alembic subcommands and thus a user would still need to have their own `[alembic]` section which would duplicate a lot of the work of this script.

3. Fundamentally I prefer an approach that does not include pyramid in order to manage the database. It should focus on the models package without using the webapp config as much as possible.

I appreciate the usefulness of a script like this... I use one myself. However for a general cookiecutter that we don't document particularly well I would like an approach that sticks very closely to the library documentation.

**Comment by russellballestrini** [comment]
I talked to @ergo in IRC and he linked to this updated version of the wrapper script: https://github.com/ergo/testscaffold/blob/master/testscaffold/scripts/migratedb.py

That said he also recommended not using this strategy and to leave schema changes to alembic and leave data manipulations / inserts using a separate console script.

**Comment by mmerickel** [comment]
thanks @russellballestrini that is where we are at in master now thanks to #7
